version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: stellara-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stellara_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./Backend
    container_name: stellara-web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    volumes:
      - ./Backend:/app
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: